apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-limit
  namespace: default
spec:
  limits:
  - default:
      cpu: 200m
      memory: 200Mi
    defaultRequest:
      cpu: 100m
      memory: 100Mi
    min:
      cpu: 50m
      memory: 50Mi
    max:
      cpu: 500m
      memory: 500Mi
    type: Container

    Okay